version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: magangkareer-postgres
    environment:
      POSTGRES_USER: magang
      POSTGRES_PASSWORD: magangpass
      POSTGRES_DB: magangkareer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: magangkareer-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
